In [3]:
import numpy as np
import pandas as pd

In [25]:
dataset = pd.read_csv('https://raw.githubusercontent.com/wlof-2/Statistic_Machine_Learning_Course/main/data/AUS_Weather.csv')

In [26]:
dataset

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow,Day,Month,Year
0,2008-12-01,Albury,13.4,22.9,0.6,4.8,8.4,W,44.0,W,...,1007.1,8.0,5.0,16.9,21.8,No,No,1,12,2008
1,2008-12-02,Albury,7.4,25.1,0.0,4.8,8.4,WNW,44.0,NNW,...,1007.8,5.0,5.0,17.2,24.3,No,No,2,12,2008
2,2008-12-03,Albury,12.9,25.7,0.0,4.8,8.4,WSW,46.0,W,...,1008.7,5.0,2.0,21.0,23.2,No,No,3,12,2008
3,2008-12-04,Albury,9.2,28.0,0.0,4.8,8.4,NE,24.0,SE,...,1012.8,5.0,5.0,18.1,26.5,No,No,4,12,2008
4,2008-12-05,Albury,17.5,32.3,1.0,4.8,8.4,W,41.0,ENE,...,1006.0,7.0,8.0,17.8,29.7,No,No,5,12,2008
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145455,2017-06-21,Uluru,2.8,23.4,0.0,4.8,8.4,E,31.0,SE,...,1020.3,5.0,5.0,10.1,22.4,No,No,21,6,2017
145456,2017-06-22,Uluru,3.6,25.3,0.0,4.8,8.4,NNW,22.0,SE,...,1019.1,5.0,5.0,10.9,24.5,No,No,22,6,2017
145457,2017-06-23,Uluru,5.4,26.9,0.0,4.8,8.4,N,37.0,SE,...,1016.8,5.0,5.0,12.5,26.1,No,No,23,6,2017
145458,2017-06-24,Uluru,7.8,27.0,0.0,4.8,8.4,SE,28.0,SSE,...,1016.5,3.0,2.0,15.1,26.0,No,No,24,6,2017
145459,2017-06-25,Uluru,14.9,22.6,0.0,4.8,8.4,W,39.0,ESE,...,1017.9,8.0,8.0,15.0,20.9,No,No,25,6,2017

In [27]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 145460 entries, 0 to 145459
Data columns (total 26 columns):
Date             145460 non-null object
Location         145460 non-null object
MinTemp          145460 non-null float64
MaxTemp          145460 non-null float64
Rainfall         145460 non-null float64
Evaporation      145460 non-null float64
Sunshine         145460 non-null float64
WindGustDir      145460 non-null object
WindGustSpeed    145460 non-null float64
WindDir9am       145460 non-null object
WindDir3pm       145460 non-null object
WindSpeed9am     145460 non-null float64
WindSpeed3pm     145460 non-null float64
Humidity9am      145460 non-null float64
Humidity3pm      145460 non-null float64
Pressure9am      145460 non-null float64
Pressure3pm      145460 non-null float64
Cloud9am         145460 non-null float64
Cloud3pm         145460 non-null float64
Temp9am          145460 non-null float64
Temp3pm          145460 non-null float64
RainToday        145460 non-null object
RainTomorrow     145460 non-null object
Day              145460 non-null int64
Month            145460 non-null int64
Year             145460 non-null int64
dtypes: float64(16), int64(3), object(7)
memory usage: 30.0+ MB

In [28]:
dataset.isnull().sum()

Date             0
Location         0
MinTemp          0
MaxTemp          0
Rainfall         0
Evaporation      0
Sunshine         0
WindGustDir      0
WindGustSpeed    0
WindDir9am       0
WindDir3pm       0
WindSpeed9am     0
WindSpeed3pm     0
Humidity9am      0
Humidity3pm      0
Pressure9am      0
Pressure3pm      0
Cloud9am         0
Cloud3pm         0
Temp9am          0
Temp3pm          0
RainToday        0
RainTomorrow     0
Day              0
Month            0
Year             0
dtype: int64

In [29]:
print(dataset.dtypes)

Date              object
Location          object
MinTemp          float64
MaxTemp          float64
Rainfall         float64
Evaporation      float64
Sunshine         float64
WindGustDir       object
WindGustSpeed    float64
WindDir9am        object
WindDir3pm        object
WindSpeed9am     float64
WindSpeed3pm     float64
Humidity9am      float64
Humidity3pm      float64
Pressure9am      float64
Pressure3pm      float64
Cloud9am         float64
Cloud3pm         float64
Temp9am          float64
Temp3pm          float64
RainToday         object
RainTomorrow      object
Day                int64
Month              int64
Year               int64
dtype: object

In [30]:
categorical = [i for i in dataset.columns if dataset[i].dtype=='object']
numerical = [i for i in dataset.columns if dataset[i].dtype=='float64' or dataset[i].dtype=='int64']

In [31]:
dataset[numerical].max()

MinTemp            33.9
MaxTemp            48.1
Rainfall          371.0
Evaporation       145.0
Sunshine           14.5
WindGustSpeed     135.0
WindSpeed9am      130.0
WindSpeed3pm       87.0
Humidity9am       100.0
Humidity3pm       100.0
Pressure9am      1041.0
Pressure3pm      1039.6
Cloud9am            9.0
Cloud3pm            9.0
Temp9am            40.2
Temp3pm            46.7
Day                31.0
Month              12.0
Year             2017.0
dtype: float64

In [34]:
dataset[numerical].mean()

MinTemp            12.192053
MaxTemp            23.215962
Rainfall            2.307990
Evaporation         5.179779
Sunshine            7.989889
WindGustSpeed      39.962189
WindSpeed9am       14.030751
WindSpeed3pm       18.669758
Humidity9am        68.901251
Humidity3pm        51.553396
Pressure9am      1017.644768
Pressure3pm      1015.250115
Cloud9am            4.659755
Cloud3pm            4.709913
Temp9am            16.987101
Temp3pm            21.668916
Day                15.712258
Month               6.399615
Year             2012.769751
dtype: float64

In [35]:
dataset[numerical].min()

MinTemp            -8.5
MaxTemp            -4.8
Rainfall            0.0
Evaporation         0.0
Sunshine            0.0
WindGustSpeed       6.0
WindSpeed9am        0.0
WindSpeed3pm        0.0
Humidity9am         0.0
Humidity3pm         0.0
Pressure9am       980.5
Pressure3pm       977.1
Cloud9am            0.0
Cloud3pm            0.0
Temp9am            -7.2
Temp3pm            -5.4
Day                 1.0
Month               1.0
Year             2007.0
dtype: float64

In [36]:
dataset[numerical].std()

MinTemp           6.365780
MaxTemp           7.088358
Rainfall          8.389771
Evaporation       3.178819
Sunshine          2.757790
WindGustSpeed    13.120931
WindSpeed9am      8.861796
WindSpeed3pm      8.716716
Humidity9am      18.855360
Humidity3pm      20.471345
Pressure9am       6.728484
Pressure3pm       6.663994
Cloud9am          2.281490
Cloud3pm          2.106768
Temp9am           6.449299
Temp3pm           6.850658
Day               8.794789
Month             3.427262
Year              2.537684
dtype: float64